import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const s = StyleSheet.create({
  page: { padding: 48, fontSize: 11, lineHeight: 1.5, color: "#1a1a1a", fontFamily: "Helvetica" },
  brand: { fontSize: 10, color: "#6d5efc", marginBottom: 4, fontFamily: "Helvetica-Bold" },
  title: { fontSize: 20, marginBottom: 16, fontFamily: "Helvetica-Bold" },
  h1: { fontSize: 15, marginTop: 14, marginBottom: 6, fontFamily: "Helvetica-Bold" },
  h2: { fontSize: 13, marginTop: 10, marginBottom: 4, fontFamily: "Helvetica-Bold" },
  p: { marginBottom: 6 },
  li: { marginBottom: 3, flexDirection: "row" },
  bullet: { width: 12 },
  foot: { position: "absolute", bottom: 24, left: 48, right: 48, fontSize: 8, color: "#999", textAlign: "center" },
});

// Minimal Markdown -> react-pdf. Handles #, ##, ###, "- " bullets, and paragraphs.
function stripInline(t: string) {
  return t.replace(/\*\*(.+?)\*\*/g, "$1").replace(/`(.+?)`/g, "$1").replace(/\[(.+?)\]\((.+?)\)/g, "$1 ($2)");
}

function render(content: string) {
  const out: React.ReactNode[] = [];
  const lines = content.split("\n");
  lines.forEach((raw, i) => {
    const line = raw.trimEnd();
    if (!line.trim()) return;
    if (line.startsWith("### ")) out.push(<Text key={i} style={s.h2}>{stripInline(line.slice(4))}</Text>);
    else if (line.startsWith("## ")) out.push(<Text key={i} style={s.h1}>{stripInline(line.slice(3))}</Text>);
    else if (line.startsWith("# ")) out.push(<Text key={i} style={s.h1}>{stripInline(line.slice(2))}</Text>);
    else if (/^[-*]\s+/.test(line))
      out.push(
        <View key={i} style={s.li}>
          <Text style={s.bullet}>•</Text>
          <Text style={{ flex: 1 }}>{stripInline(line.replace(/^[-*]\s+/, ""))}</Text>
        </View>
      );
    else out.push(<Text key={i} style={s.p}>{stripInline(line)}</Text>);
  });
  return out;
}

export function Report({ title, content }: { title: string; content: string }) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <Text style={s.brand}>MICROMANUS · DEEP RESEARCH REPORT</Text>
        <Text style={s.title}>{title}</Text>
        {render(content)}
        <Text style={s.foot} fixed>Generated by MicroManus — verify sources before relying on this report.</Text>
      </Page>
    </Document>
  );
}
